import React, { useState } from "react";
import "../../../assets/reports.css";

function RecentReports({ reports }) {
const [search, setSearch] = useState("");
const [sortAsc, setSortAsc] = useState(false);
const filteredReports = [...(reports || [])]
  .filter((report) =>
    report.name.toLowerCase().includes(search.toLowerCase()) ||
    report.type.toLowerCase().includes(search.toLowerCase()) ||
    report.user.toLowerCase().includes(search.toLowerCase())
  )
  .sort((a, b) => {
    if (sortAsc) {
      return new Date(a.date) - new Date(b.date);
    }
    return new Date(b.date) - new Date(a.date);
  });
return (

<div className="recent-reports-card">

<div className="recent-header">

<div>
<h3>Recent Reports</h3>

<p>
Last generated reports across all categories
</p>

</div>


<div className="recent-actions">

<input
  placeholder="Search reports..."
  value={search}
  onChange={(e) => setSearch(e.target.value)}
/>

<button onClick={() => setSortAsc(!sortAsc)}>
  {sortAsc ? "Oldest First" : "Newest First"}
</button>

</div>

</div>


<table>

<thead>

<tr>
<th>Report Name</th>
<th>Report Type</th>
<th>Generated By</th>
<th>Generated Date</th>
<th>Format</th>
<th>Download</th>
</tr>

</thead>


<tbody>

{
filteredReports.map((item, index) => (

<tr key={index}>

<td>{item.name}</td>

<td>{item.type}</td>

<td>{item.user}</td>

<td>{item.date}</td>

<td>{item.format}</td>

<td>
<button className="download-btn">
Download
</button>
</td>

</tr>

))
}

</tbody>

</table>

</div>

)

}

export default RecentReports;