from app.models import Obligation, Assignee

SARAH = Assignee(name="Sarah Chen", initials="SC", color="blue")
LISA = Assignee(name="Lisa Torres", initials="LT", color="purple")
DAVID = Assignee(name="David Park", initials="DP", color="green")
JAMES = Assignee(name="James Lee", initials="JL", color="red")
MARK = Assignee(name="Mark Johnson", initials="MJ", color="orange")

OBLIGATIONS: list[Obligation] = [
    Obligation(
        id="OBL-001",
        title="Q2 Compliance Report Submission",
        contract="Master Services Agreement — Accenture LLP",
        assignee=SARAH,
        due_date="Jun 30, 2024",
        priority="High",
        status="In Progress",
        tag="Reporting",
    ),
    Obligation(
        id="OBL-002",
        title="Annual Insurance Certificate Renewal",
        contract="Commercial Lease — HQ Tower A",
        assignee=LISA,
        due_date="May 15, 2024",
        priority="Critical",
        status="Overdue",
        tag="Insurance",
    ),
    Obligation(
        id="OBL-003",
        title="GDPR Data Audit Completion",
        contract="GDPR Data Processing Agreement",
        assignee=DAVID,
        due_date="Jul 1, 2024",
        priority="High",
        status="Pending",
        tag="Audit",
    ),
    Obligation(
        id="OBL-004",
        title="APAC Vendor Performance Review",
        contract="APAC Distribution Agreement",
        assignee=JAMES,
        due_date="Jun 15, 2024",
        priority="Medium",
        status="Under Review",
        tag="Review",
    ),
    Obligation(
        id="OBL-005",
        title="Salesforce License Renewal Decision",
        contract="Enterprise SaaS License — Salesforce",
        assignee=MARK,
        due_date="Nov 1, 2024",
        priority="Medium",
        status="Pending",
        tag="Renewal",
    ),
    Obligation(
        id="OBL-006",
        title="Executive Compensation Adjustment",
        contract="Executive Employment Agreement",
        assignee=DAVID,
        due_date="Sep 1, 2024",
        priority="High",
        status="Pending",
        tag="HR",
    ),
    Obligation(
        id="OBL-007",
        title="Q2 Lease Payment — Metropolitan REIT",
        contract="Commercial Lease — HQ Tower A",
        assignee=LISA,
        due_date="Jun 1, 2024",
        priority="Critical",
        status="Completed",
        tag="Payment",
    ),
    Obligation(
        id="OBL-008",
        title="NDA Scope Review — Partnership Terms",
        contract="Mutual NDA — TechVenture Group",
        assignee=SARAH,
        due_date="Aug 10, 2024",
        priority="Low",
        status="Pending",
        tag="Review",
    ),
    Obligation(
        id="OBL-009",
        title="AWS Usage Compliance Report",
        contract="Cloud Infrastructure Agreement",
        assignee=MARK,
        due_date="Jul 15, 2024",
        priority="Medium",
        status="In Progress",
        tag="Reporting",
    ),
    Obligation(
        id="OBL-010",
        title="Marketing Campaign Legal Review",
        contract="Marketing Agency Retainer",
        assignee=SARAH,
        due_date="Jun 20, 2024",
        priority="Low",
        status="Completed",
        tag="Review",
    ),
]
